# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-13 09:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('email_address', models.EmailField(help_text='Email of user who used Trial Service', max_length=254, unique=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_user', to='resume.Resume')),
            ],
            options={
                'abstract': False,
            },
        ),

    ]


