# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-13 09:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_trialuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialuser',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='trial_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_user', to='resume.TrialUser'),
        ),
    ]
