# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-14 05:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170313_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialuser',
            name='email_address',
            field=models.EmailField(help_text='Email of user who used Trial Service', max_length=254),
        ),
    ]
