# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-16 08:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20170316_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='company',
            field=models.CharField(help_text='Company the user is currently working in.', max_length=50, null=True),
        ),
    ]
