# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-20 09:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20170316_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
