# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-27 08:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_location',
            field=models.URLField(help_text='Path to resume', null=True),
        ),
    ]
