# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-31 08:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_resume_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total Score Obtained', max_digits=250),
        ),
    ]
