# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-31 08:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resume_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Individual Score Obtained', max_digits=250),
        ),
    ]
