# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-03 09:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hireable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
