# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-05 16:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20170404_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='customer_rating_for_all_version_ios',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='customer_rating_for_current_version_ios',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='installs_android',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='rating_ios',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='ratings_android',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='total_customer_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
