# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-13 15:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20170405_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='hireable',
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
