# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-15 08:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20170413_1507'),
        # ('resume', '0014_remove_resume_hireable'),
    ]

    operations = [
    ]
