# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 07:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20170413_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='institution',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
