# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_auto_20170522_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
