# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_auto_20170522_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Location'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Location'),
        ),
    ]
