# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20170522_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rank',
            field=models.FloatField(default=None, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='score',
            field=models.FloatField(default=None, null=True, blank=True),
        ),
    ]
