# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_auto_20170523_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
