# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20170523_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='company',
        ),
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.ManyToManyField(to='resume.Company'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='institution',
        ),
        migrations.AddField(
            model_name='resume',
            name='institution',
            field=models.ManyToManyField(to='resume.Institution'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.ManyToManyField(to='resume.Location'),
        ),
    ]
