# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:37


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_auto_20170525_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='institution',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
    ]
