# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-30 12:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_auto_20170530_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='location',
            new_name='locations',
        ),
    ]
