# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-30 14:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_auto_20170530_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
