# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-06 08:13


from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0028_resume_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=40)),
                ('query_string', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_active', models.DateTimeField()),
                ('referer', models.URLField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=100)),
                ('pageview', models.CharField(blank=True, max_length=40)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_id',
        ),
    ]
