# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-05 07:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_resume_job_id'),
        ('resume', '0015_merge'),
    ]

    operations = [
    ]
