# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-06 09:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_auto_20170606_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
