# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-06 13:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_merge'),
        ('resume', '0030_auto_20170606_0949'),
    ]

    operations = [
    ]
