# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-08 10:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0031_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='referer',
            field=models.TextField(blank=True),
        ),
    ]
