# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-23 13:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='limit',
            field=models.PositiveIntegerField(default=0, help_text='Can access the service till limit count exceeds'),
        ),
    ]
